/*
 * Automatically generated by ./lib/build_OID_registry.  Do not edit
 */

static const unsigned short oid_index[OID__NR + 1] = {
	[OID_id_dsa_with_sha1] = 0,
	[OID_id_dsa] = 7,
	[OID_id_ecdsa_with_sha1] = 14,
	[OID_id_ecPublicKey] = 21,
	[OID_rsaEncryption] = 28,
	[OID_md2WithRSAEncryption] = 37,
	[OID_md3WithRSAEncryption] = 46,
	[OID_md4WithRSAEncryption] = 55,
	[OID_sha1WithRSAEncryption] = 64,
	[OID_sha256WithRSAEncryption] = 73,
	[OID_sha384WithRSAEncryption] = 82,
	[OID_sha512WithRSAEncryption] = 91,
	[OID_sha224WithRSAEncryption] = 100,
	[OID_data] = 109,
	[OID_signed_data] = 118,
	[OID_email_address] = 127,
	[OID_content_type] = 136,
	[OID_messageDigest] = 145,
	[OID_signingTime] = 154,
	[OID_smimeCapabilites] = 163,
	[OID_smimeAuthenticatedAttrs] = 172,
	[OID_md2] = 183,
	[OID_md4] = 191,
	[OID_md5] = 199,
	[OID_msIndirectData] = 207,
	[OID_msPeImageDataObjId] = 217,
	[OID_msIndividualSPKeyPurpose] = 227,
	[OID_msOutlookExpress] = 237,
	[OID_certAuthInfoAccess] = 246,
	[OID_sha1] = 254,
	[OID_sha256] = 259,
	[OID_commonName] = 268,
	[OID_surname] = 271,
	[OID_countryName] = 274,
	[OID_locality] = 277,
	[OID_stateOrProvinceName] = 280,
	[OID_organizationName] = 283,
	[OID_organizationUnitName] = 286,
	[OID_title] = 289,
	[OID_description] = 292,
	[OID_name] = 295,
	[OID_givenName] = 298,
	[OID_initials] = 301,
	[OID_generationalQualifier] = 304,
	[OID_subjectKeyIdentifier] = 307,
	[OID_keyUsage] = 310,
	[OID_subjectAltName] = 313,
	[OID_issuerAltName] = 316,
	[OID_basicConstraints] = 319,
	[OID_crlDistributionPoints] = 322,
	[OID_certPolicies] = 325,
	[OID_authorityKeyIdentifier] = 328,
	[OID_extKeyUsage] = 331,
	[OID__NR] = 334
};

static const unsigned char oid_data[334] = {
	42, 134, 72, 206, 46, 4, 3, 	// id_dsa_with_sha1
	42, 134, 72, 206, 56, 4, 1, 	// id_dsa
	42, 134, 72, 206, 61, 4, 1, 	// id_ecdsa_with_sha1
	42, 134, 72, 206, 61, 2, 1, 	// id_ecPublicKey
	42, 134, 72, 134, 247, 13, 1, 1, 1, 	// rsaEncryption
	42, 134, 72, 134, 247, 13, 1, 1, 2, 	// md2WithRSAEncryption
	42, 134, 72, 134, 247, 13, 1, 1, 3, 	// md3WithRSAEncryption
	42, 134, 72, 134, 247, 13, 1, 1, 4, 	// md4WithRSAEncryption
	42, 134, 72, 134, 247, 13, 1, 1, 5, 	// sha1WithRSAEncryption
	42, 134, 72, 134, 247, 13, 1, 1, 11, 	// sha256WithRSAEncryption
	42, 134, 72, 134, 247, 13, 1, 1, 12, 	// sha384WithRSAEncryption
	42, 134, 72, 134, 247, 13, 1, 1, 13, 	// sha512WithRSAEncryption
	42, 134, 72, 134, 247, 13, 1, 1, 14, 	// sha224WithRSAEncryption
	42, 134, 72, 134, 247, 13, 1, 7, 1, 	// data
	42, 134, 72, 134, 247, 13, 1, 7, 2, 	// signed_data
	42, 134, 72, 134, 247, 13, 1, 9, 1, 	// email_address
	42, 134, 72, 134, 247, 13, 1, 9, 3, 	// content_type
	42, 134, 72, 134, 247, 13, 1, 9, 4, 	// messageDigest
	42, 134, 72, 134, 247, 13, 1, 9, 5, 	// signingTime
	42, 134, 72, 134, 247, 13, 1, 9, 15, 	// smimeCapabilites
	42, 134, 72, 134, 247, 13, 1, 9, 16, 2, 11, 	// smimeAuthenticatedAttrs
	42, 134, 72, 134, 247, 13, 2, 2, 	// md2
	42, 134, 72, 134, 247, 13, 2, 4, 	// md4
	42, 134, 72, 134, 247, 13, 2, 5, 	// md5
	43, 6, 1, 4, 1, 130, 55, 2, 1, 4, 	// msIndirectData
	43, 6, 1, 4, 1, 130, 55, 2, 1, 15, 	// msPeImageDataObjId
	43, 6, 1, 4, 1, 130, 55, 2, 1, 21, 	// msIndividualSPKeyPurpose
	43, 6, 1, 4, 1, 130, 55, 16, 4, 	// msOutlookExpress
	43, 6, 1, 5, 5, 7, 1, 1, 	// certAuthInfoAccess
	43, 14, 3, 2, 26, 	// sha1
	96, 134, 72, 1, 101, 3, 4, 2, 1, 	// sha256
	85, 4, 3, 	// commonName
	85, 4, 4, 	// surname
	85, 4, 6, 	// countryName
	85, 4, 7, 	// locality
	85, 4, 8, 	// stateOrProvinceName
	85, 4, 10, 	// organizationName
	85, 4, 11, 	// organizationUnitName
	85, 4, 12, 	// title
	85, 4, 13, 	// description
	85, 4, 41, 	// name
	85, 4, 42, 	// givenName
	85, 4, 43, 	// initials
	85, 4, 44, 	// generationalQualifier
	85, 29, 14, 	// subjectKeyIdentifier
	85, 29, 15, 	// keyUsage
	85, 29, 17, 	// subjectAltName
	85, 29, 18, 	// issuerAltName
	85, 29, 19, 	// basicConstraints
	85, 29, 31, 	// crlDistributionPoints
	85, 29, 32, 	// certPolicies
	85, 29, 35, 	// authorityKeyIdentifier
	85, 29, 37, 	// extKeyUsage
};

static const struct {
	unsigned char hash;
	enum OID oid : 8;
} oid_search_table[OID__NR] = {
	[  0] = {  10, OID_title                               }, // 55040c
	[  1] = {  23, OID_issuerAltName                       }, // 551d12
	[  2] = {  23, OID_initials                            }, // 55042b
	[  3] = {  29, OID_md2WithRSAEncryption                }, // 2a864886f70d010102
	[  4] = {  30, OID_md2                                 }, // 2a864886f70d0202
	[  5] = {  32, OID_id_dsa_with_sha1                    }, // 2a8648ce2e0403
	[  6] = {  35, OID_content_type                        }, // 2a864886f70d010903
	[  7] = {  35, OID_sha256WithRSAEncryption             }, // 2a864886f70d01010b
	[  8] = {  36, OID_authorityKeyIdentifier              }, // 551d23
	[  9] = {  37, OID_description                         }, // 55040d
	[ 10] = {  43, OID_id_dsa                              }, // 2a8648ce380401
	[ 11] = {  51, OID_msIndividualSPKeyPurpose            }, // 2b060104018237020115
	[ 12] = {  54, OID_basicConstraints                    }, // 551d13
	[ 13] = {  54, OID_generationalQualifier               }, // 55042c
	[ 14] = {  60, OID_md3WithRSAEncryption                }, // 2a864886f70d010103
	[ 15] = {  64, OID_signed_data                         }, // 2a864886f70d010702
	[ 16] = {  77, OID_countryName                         }, // 550406
	[ 17] = {  77, OID_id_ecdsa_with_sha1                  }, // 2a8648ce3d0401
	[ 18] = {  83, OID_sha256                              }, // 608648016503040201
	[ 19] = {  85, OID_smimeCapabilites                    }, // 2a864886f70d01090f
	[ 20] = {  87, OID_sha1                                }, // 2b0e03021a
	[ 21] = {  97, OID_email_address                       }, // 2a864886f70d010901
	[ 22] = { 106, OID_extKeyUsage                         }, // 551d25
	[ 23] = { 106, OID_msPeImageDataObjId                  }, // 2b06010401823702010f
	[ 24] = { 110, OID_locality                            }, // 550407
	[ 25] = { 126, OID_rsaEncryption                       }, // 2a864886f70d010101
	[ 26] = { 132, OID_smimeAuthenticatedAttrs             }, // 2a864886f70d010910020b
	[ 27] = { 142, OID_id_ecPublicKey                      }, // 2a8648ce3d0201
	[ 28] = { 142, OID_sha224WithRSAEncryption             }, // 2a864886f70d01010e
	[ 29] = { 143, OID_stateOrProvinceName                 }, // 550408
	[ 30] = { 146, OID_subjectKeyIdentifier                }, // 551d0e
	[ 31] = { 160, OID_data                                }, // 2a864886f70d010701
	[ 32] = { 161, OID_crlDistributionPoints               }, // 551d1f
	[ 33] = { 173, OID_msOutlookExpress                    }, // 2b0601040182371004
	[ 34] = { 179, OID_keyUsage                            }, // 551d0f
	[ 35] = { 195, OID_md4WithRSAEncryption                }, // 2a864886f70d010104
	[ 36] = { 198, OID_certPolicies                        }, // 551d20
	[ 37] = { 201, OID_organizationName                    }, // 55040a
	[ 38] = { 204, OID_messageDigest                       }, // 2a864886f70d010904
	[ 39] = { 204, OID_sha384WithRSAEncryption             }, // 2a864886f70d01010c
	[ 40] = { 212, OID_name                                }, // 550429
	[ 41] = { 213, OID_commonName                          }, // 550403
	[ 42] = { 220, OID_md4                                 }, // 2a864886f70d0204
	[ 43] = { 226, OID_sha1WithRSAEncryption               }, // 2a864886f70d010105
	[ 44] = { 227, OID_md5                                 }, // 2a864886f70d0205
	[ 45] = { 228, OID_certAuthInfoAccess                  }, // 2b06010505070101
	[ 46] = { 234, OID_organizationUnitName                }, // 55040b
	[ 47] = { 237, OID_signingTime                         }, // 2a864886f70d010905
	[ 48] = { 237, OID_sha512WithRSAEncryption             }, // 2a864886f70d01010d
	[ 49] = { 244, OID_surname                             }, // 550404
	[ 50] = { 245, OID_subjectAltName                      }, // 551d11
	[ 51] = { 245, OID_givenName                           }, // 55042a
	[ 52] = { 255, OID_msIndirectData                      }, // 2b060104018237020104
};
