/*
 * Automatically generated by asn1_compiler.  Do not edit
 *
 * ASN.1 parser for x509_rsakey
 */
#include "asn1_decoder.h"

extern const struct asn1_decoder x509_rsakey_decoder;

extern int rsa_extract_mpi(void *, size_t, unsigned char, const void *, size_t);

